number_of_rooms = "2"
area = "etten-leur"
min_price = "800"
max_price = "1100"
dbFileName = "database.db"
EmailBody = ""
mailUser="#######"
mailPassword="######"
mailSubject="Resultados busqueda de casa"
sendEmailFlag = False
mailReceiver='#######'
